language: python
dist: trusty
python:
  - pypy
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - pip install tox-travis
script:
  - tox
after_success:
  - test "${TRAVIS_TAG}" != "" && docs/deploy.sh
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: jfinkhaeuser
  password:
    secure: "kJpa/uKBQA4gZIMikkSOMblDgYK9g8ZKuierSUVzWfG5Yc1pXemrXhZWhJx68bX2U1rIDm2vwXYUqzpcAAD7fhQWw4Plpp1Pa0Mux7JeLA7+pDeV3JAJXq/H+V7JFfNMXMpg3PRd6U5p1GowtsU/DHmM5aDfTURfEx00F1YLn5ncRcAboN3Wf4s2Z5YeOedYYHHYomhWyUR8X+BC1R7BHNNXUKlRmgqtUVZBfJIhLLquNe/O1dZiG5Jh0qnYESOXpCE/yhFBkpw3IWIwkSCFlJEcSGfMgki+7jGXhBHVzHtWilTeyibhTqTCJP200GJPRff/Bwu2BNwC4WD78pxhZOUiza7dy0Y4/KJsBzQkWt9duWRTUntRPuV8yHpRlO1ZVtaLMTBzI9bLIbmR8ff0gesd8Jbj2aa66kuOLDXNYYeJuzezFZptk29KG0ZHHRJDZhpM44Pvd9Fh6WQ3J5r1g+KDboei97dxjTwkPX7iNJsZALdogAJCInd6IOwn0G14sOdkHmE8f5oZ4XLo0+FoAj7lAUoK6MT/VS5xagE7/0TCTGrcNVHnk20ijxkuB53R4apRIreGEyZxMGTOtfRT9vOjUNFA0e8pEK4UOuvSuquNG++TsiJfjZ/qASFn16EQhpnPLvnevAEPUQH/mksSrASHYVxktpgujZErXuV5zr8="
  on:
    tags: true
    branch: master
    repo: jfinkhaeuser/bran
    condition: "$(python --version | grep '^Python 3\\.5')"
env:
  global:
    secure: "R4C7vL3/Wl4s7gLbpijYvzIzeK5hpys4ENtVg8kS2UayB6Lv/Qk1+3cO6ciKslk1QiBU4Qth76BZMCNnySviBCak6+7oBtjzwtB5xKHKrZcbKL1WcdMN1k/yUpXdoe/eGflTtpHjhUxZ9uD9wjb0YFMRsfWVXQ4NDPhv63DaBWZY7fF24ScxNY0bLKSAWcs99HMayp3sbgStiQYERcVZsJa9bH8IyC3LUotGT6RhWAet+RGjOOr+Q0mrI8x+DUezPrSi4yCV7kqoX6CS8qzfd8nPKLpdK1sh1Gl/qE6VCIgkq7gwtPRx/3hN/c1icSAp+wc+C845Mr50qjMIUY/6SOEPA3/nt+G9rOoAJdcKZr5Hivytd+DDfTHgBQyJl/amaNRMFDK6IvcKRWIfnmVTSfwlmXXMXuzpXWecXFK2Y5GjSJULJ78uehNegwrx5AQI0LMOBsRtlmISYlIXj79L/3yCHGGzzIyn8+yADAHFoH6Y/2ScsMc06zYkincVit4EtaecdxlEsXFALAAmoRA5hmQ2FAOkE53mmEOkkEuiSjeZ5+P4LtK2llPru0BhSndHHjO4djHnbvh1Gj7HCD17TEL7YlcFWobEAsrnBAIkQknItjHxusLMV292xBC4O2lXU/OD/pi0W6DpMqyTELWwI5D9KRv4PsBvmrFbeS8cxqE="

